outputs: outputs/log/two_stage/bagnet

bb_env: bb_envs/src/ngspice/envs/two_stage_opamp_w_rz.yaml

agent_cls: bagnet.agent.bagnet.BagNetAgent
agent_params:
  seed: 20
  n_init_samples: 100
  max_n_steps: 1000
  k: 100
  max_iter: 20000
  n_new_samples: 5
  ref_dsn_idx: 20
  valid_frac: 0.2
  batch_size: 64
  display_step: 100
  ckpt_step: 100

  model_cls: bagnet.model.dropout.DropOutModel
  model_params:
    feat_ext_hidden_dim_list: [20, 20]
    compare_nn_hidden_dim_list: [20]
    learning_rate: !!float 0.001
    keep_prob: !!float 0.8

ea_cls: bagnet.ea.custom.CustomEA
ea_params:
  cxpb: 0.6
  mutpb: 0.4
